kotlin.code.style=official

# Plugin versions
kotlinVersion=2.4.20
kotlinterVersion=5.7.0

# Dependency versions
exposedVersion=1.5.0
flywayCoreVersion=13.9.0
hagDomeneInntektsmeldingVersion=0.11.3
hikariVersion=7.1.0
kafkaClientVersion=4.3.1
kotestVersion=6.2.5
kotlinxSerializationVersion=1.11.0
logbackVersion=1.6.5
mockkVersion=1.14.11
postgresqlVersion=42.7.13
rapidsAndRiversVersion=2026091610031789545782
testcontainersVersion=2.0.5
utilsVersion=0.10.2
