package no.nav.helsearbeidsgiver.bro.sykepenger

object Event {
    const val TRENGER_OPPLYSNINGER_FRA_ARBEIDSGIVER = "TRENGER_OPPLYSNINGER_FRA_ARBEIDSGIVER"
    const val TRENGER_FORESPOERSEL = "TRENGER_FORESPØRSEL"
    const val FORESPOERSEL_SVAR = "FORESPØRSEL_SVAR"
    const val FORESPOERSEL_MOTTATT = "FORESPØRSEL_MOTTATT"
}
