apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helsearbeidsgiver-bro-sykepenger
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
    app: helsearbeidsgiver-bro-sykepenger
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    timeout: 2
  readiness:
    path: isready
    initialDelay: 10
    timeout: 2
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  envFrom:
    - secret: google-sql-helsearbeidsgiver-bro-sykepenger
    - secret: simba-pilot-tillatte-organisasjoner
  env:
    - name: GCP_PRJ_ID
      value: helsearbeidsgiver-dev-6d06
    - name: KAFKA_CONSUMER_GROUP_ID
      value: helsearbeidsgiver-bro-sykepenger-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.arbeidsgiveropplysninger
    - name: KAFKA_EXTRA_TOPIC
      value: helsearbeidsgiver.pri
    - name: SPINN_SCOPE
      value: "api://dev-fss.helsearbeidsgiver.syfoinntektsmelding/.default"
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: helsearbeidsgiver-bro-sykepenger
