name: Build and deploy dev

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    uses: navikt/hag-workflows/.github/workflows/build-and-deploy.yml@nais-apply
    permissions:
      id-token: write
    with:
      environment: dev
      project-id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      identity-provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
