name: Monitor dependencies with Dependabot

on:
  schedule:
    # Hver mandag, onsdag og fredag kl. 04:00
    - cron: '0 4 * * 1,3,5'
  push:
    branches:
      - main
    paths:
      - gradle.properties
      - build.gradle.kts
      - settings.gradle.kts

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
