name: Produksjon

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      docker_image: ${{ steps.docker_push.outputs.image }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v5

      - name: Build and test
        run: ./gradlew build test jar --console=plain
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker_push
        with:
          team: helsearbeidsgiver
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-to-prod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          WORKLOAD_IMAGE: ${{ needs.build.outputs.docker_image }}
          RESOURCE: deploy/nais.yml
          VARS: deploy/prod.yml
